# Generated by Django 4.0.1 on 2022-02-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
