# Generated by Django 4.0.1 on 2022-02-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_online',
        ),
    ]
