# Generated by Django 4.0.1 on 2022-02-21 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
